version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  mageai:
    container_name: mageai
    image: mageai/mageai
    depends_on:
      - db
    ports:
      - 6789:6789
      - 80:80
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
    command: /app/run_app.sh mage start mageai_demo
    volumes:
      - ./mageai_demo:/home/src/mageai_demo
    links:
      - db
volumes:
  db:
    driver: local